apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: digit-link
  namespace: argocd
  # Note: Image updater annotations removed - using ImageUpdater CR (v1.0+)
  # See image-updater.yaml for configuration
spec:
  project: default
  source:
    repoURL: https://github.com/nickvdm/digit-link.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dzone-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
