apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dzone-dev
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  - tcp-tunnel.yaml
images:
  - name: ghcr.io/niekvdm/digit-link
    newTag: v0.3.9
    newName: ghcr.io/niekvdm/digit-link
